import json
from datetime import datetime, timedelta
from googleapiclient.discovery import build

from agents.email_reader import authenticate_gmail
from logger import get_logger


logger = get_logger(__name__)


def create_calendar_event(analysis):
    logger.info("Creating calendar event")

    task = analysis.get("task", "Email Task")
    deadline = analysis.get("deadline")

    creds = authenticate_gmail()

    service = build("calendar", "v3", credentials=creds)

    # Default start time
    start = datetime.utcnow()

    # Handle simple deadline cases
    if deadline and "tomorrow" in deadline.lower():
        start = datetime.utcnow() + timedelta(days=1)

    end = start + timedelta(hours=1)

    event = {
        "summary": task,
        "description": f"Generated by AI Email Agent\nDeadline: {deadline}",
        "start": {
            "dateTime": start.isoformat(),
            "timeZone": "UTC",
        },
        "end": {
            "dateTime": end.isoformat(),
            "timeZone": "UTC",
        },
    }

    event = service.events().insert(
        calendarId="primary",
        body=event
    ).execute()

    logger.info(f"Calendar event created: {event.get('htmlLink')}")
